paths:
  /api/products/{PID}:
    get:
      summary: Muestra los detalles del producto enviado por pid.
      tags:
        - Productos
      requestBody:
        required: true
        # content:
        #   application/json:
        #     schema:
        #       $ref: '#/components/requestBodies/schemaProducts'
      responses:
        "201":
          description: Producto encontrado.
          content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/schemaProducts'
        "404":
          description: Producto no encontrado.
       