paths:
  /api/products:
    get:
      summary: Muestra una lista ordenada y con posibilidad de filtrarla, de todos los productos.
      tags:
        - Productos
      responses:
        "200":
          description: Productos correctamente.
        "500":
          description: Productos no encontrados.