paths:
  /api/products/{PID}:
    put:
      summary: Ruta con metodo put para modificar el producto espeficidado por pid.
      tags:
        - Productos
      requestBody:
        required: true
        # content:
        #   application/json:
        #     schema:
        #       $ref: '#/components/requestBodies/schemaProducts'
      responses:
        "201":
          description: Producto modificado correctamente.
        "404":
          description: Producto no encontrado.
       