paths:
  /api/products/productSelected/{PID}:
    put:
      summary: Ruta de modificacion de productos trabajada con socket.io para /realtimeproducts.
      tags:
        - Productos
      requestBody:
        required: true
        # content:
        #   application/json:
        #     schema:
        #       $ref: '#/components/requestBodies/schemaProducts'
      responses:
        "201":
          description: Producto modificado correctamente.
        "404":
          description: Producto no encontrado.
       